### ISSUE TITLE
Issues with filtering for api/genesis/address

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-explorer#184] opened 2019-11-29 12:04 UTC
Querying `http://localhost:8100/api/genesis/address?pageSize=20&page=2`  will return list of adresses where each of them has **"cgaiIsRedeemed":false**  

```
{
	"Right": [
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZB2zrbrdDkQNPdCndghMUJN8o8XjMaJ1jXgwVevf7TUrdmsSP",
			"cgaiGenesisAmount": {
				"getCoin": "781381495000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ9dH9VC4iVXZRNYe5HGc73AKVMYHExpgYBmDMkgCUgnJGqqqq",
			"cgaiGenesisAmount": {
				"getCoin": "648176763000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZK3YTwof6pQ7dyR7gvAjEFuUJFtDmwkrF1kVBzw7ZhYCdviTw",
			"cgaiGenesisAmount": {
				"getCoin": "300149999000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ9X7cASSFNG6w2xRzWaEkLojLteLzKNgo26NGAMJ1vCKisd7Y",
			"cgaiGenesisAmount": {
				"getCoin": "132113541000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZCo1gun5HbfcEdEWyVSLc7uj8Tg8U9NhMCfDRWqGsSRce2Uka",
			"cgaiGenesisAmount": {
				"getCoin": "131406876000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ4zU46CcMwd6QZLf23jyHLdNLcEBua9QAeKX8DyMV5m4o6HYE",
			"cgaiGenesisAmount": {
				"getCoin": "123701030000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZK77edAqpNaPVhaUfTCcoaGepvQPDrSuX1czw5uZmp47F1k73",
			"cgaiGenesisAmount": {
				"getCoin": "115384615000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ11hWKCn4n66gusxDhXwRee3xxfXA1w3KTM6qD514E9xjb4rG",
			"cgaiGenesisAmount": {
				"getCoin": "109831430000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ3ix6Xs1tLa4vKmUHYLnwtyDwnp2gyKB58MMTsitgj4SFSZTX",
			"cgaiGenesisAmount": {
				"getCoin": "103431730000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZNEEuiFn5BjuCDbw1KVLEjnMp47UZp2PP4E7v7v2u6F31VJfx",
			"cgaiGenesisAmount": {
				"getCoin": "101363636000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ4VEgkqXHqk41FiSFbwxjhSwGsibzF2S3tpv7NvvLG8Kj1DW6",
			"cgaiGenesisAmount": {
				"getCoin": "87373125000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ4smketL8fm5dKMTwZALiCeuQroYRr6CeJBA3tQzR8MT5gpAV",
			"cgaiGenesisAmount": {
				"getCoin": "84885536000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ3MBDocNEA9H41bPA4MRtc1N4jdgUzWQCqN6g6EXmQ49fU8eE",
			"cgaiGenesisAmount": {
				"getCoin": "82024819000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ7tCytKv8Qx4DsLPBoEiYadjEbMQSASZmZDNCfYFVCWUcaKKU",
			"cgaiGenesisAmount": {
				"getCoin": "76651905000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZBgmcp7jtA3jTqg8HfnjNYdm9Ln33PT3gZVoYp9HeZ3kxtVTZ",
			"cgaiGenesisAmount": {
				"getCoin": "75692998000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ43NhMYvw1bkcGnEzdDbm9QTWiRux6Xpy8sorgfSJfazneEsP",
			"cgaiGenesisAmount": {
				"getCoin": "68681632000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZEcMcWsyCiW74DEDmdyuE7A6GeTCZ8NYP7A7hxKAdQxonMwo7",
			"cgaiGenesisAmount": {
				"getCoin": "66714570000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZMB92JqgxAEWfXJo6Ex7wWLoS7REmh81Ue6GgsNrDNs3MeQKA",
			"cgaiGenesisAmount": {
				"getCoin": "63598711000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZ5sz3qbLRZpJZ7nQbV4HdA95yNsummkfWzyEgHhrjx1za5KHg",
			"cgaiGenesisAmount": {
				"getCoin": "62363921000000"
			},
			"cgaiIsRedeemed": false
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZGArcqwLkxS8mjCeByh5gVF2jWbC4FTC5YF4NULWPW2ZuCdq5",
			"cgaiGenesisAmount": {
				"getCoin": "59999882000000"
			},
			"cgaiIsRedeemed": false
		}
	]
}
```

... now same query but with added filter `http://localhost:8100/api/genesis/address?pageSize=20&page=2&filter=redeemed`  returns:

```
{
	"Right": [
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZC5VVyF7QntbTXEhF1FnEY2XF4Bb7uPRi6CsTJBoR8fLwNU1q",
			"cgaiGenesisAmount": {
				"getCoin": "1000000"
			},
			"cgaiIsRedeemed": true
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZAN64wuATkJCH5xUuJ95PYhfz72BmoEiyP392QaD5mjcXJiBD",
			"cgaiGenesisAmount": {
				"getCoin": "1000000"
			},
			"cgaiIsRedeemed": true
		},
		{
			"cgaiCardanoAddress": "Ae2tdPwUPEZJHU4Nkqo1W6pxPWrcBBv5NfeTBYssJWTjp2iJUnjGP5A5ApT",
			"cgaiGenesisAmount": {
				"getCoin": "1000000"
			},
			"cgaiIsRedeemed": true
		}
	]
}
```
If there was no redeemed entries on previous list, why they appeared after filtering exactly the same list ? Is this a bug ?

**Comment by erikd** [comment] 2020-01-13 07:07
> Querying http://localhost:8100/api/genesis/address?pageSize=20&page=2 will return list of adresses where each of them has "cgaiIsRedeemed":false

Are you running this on mainnet or a testnet? On the mainnet, I cannot reproduce this.

On mainnet most entries for that query have `"cgaiIsRedeemed": true`.

If the query is performed without a `filter` parameter, *all* genesis addresses are returned. However, on mainnet, the majority of these are redeemed (which may not be true on testnet). As you have seen, valid values for the `query` parameter are: `redeemed`, `notredeemed` and `all`.

**Comment by erikd** [comment] 2020-01-20 01:58
Closing this because it seems invalid and I have not gotten a response.

**Closed as completed by erikd** 2020-01-20 01:58 UTC
Labels: invalid

**Comment by ArturWieczorek** [comment] 2020-01-20 21:47
@erikd Sorry for late reply, I was not able to reproduce it, also - next time I will remember about adding details about environment, revision  etc.
