### ISSUE TITLE
Another failure log for build cardano-tx-submit-webapi

### ISSUE THREAD

**Issue by johndoe0x** [input-output-hk/cardano-explorer#280] opened 2020-03-11 11:00 UTC
OS : ubuntu-bionic
Enviroment : docker container 

cabal version : 
cabal-install version 3.0.1.0
compiled using version 3.0.2.0 of the Cabal library 

ghc version : 
The Glorious Glasgow Haskell Compilation System, version 8.6.5

running command below. 
```
cabal run cardano-tx-submit-webapi -- \
    --config config/tx-submit-mainnet-config.yaml \
    --genesis-file ../cardano-node/configuration/mainnet-genesis.json \
    --socket-path ../cardano-node/state-node-mainnet/node.socket \
    --port 8101
```

failure log below.  

```
HEAD is now at a7b403c Merge pull request #82 from input-output-hk/erikd/deps-20200215
HEAD is now at 2547ad1 Merge pull request #65 from dcoutts/dcoutts/drop-vrf-p256-openssl
HEAD is now at 172b49f Merge pull request #728 from input-output-hk/erikd/deps-20200225
HEAD is now at 318f5a15 Merge pull request #1204 from input-output-hk/jc/1202/block-nos
HEAD is now at 57fcc83 Merge #97
HEAD is now at bc3563c Update CODEOWNERS (#357)
HEAD is now at 43a036c Replace Universum with Cardano.Prelude
HEAD is now at 26d35ad Add SeedGoblin instance for `Maybe a`
HEAD is now at 49b347d Merge #514
HEAD is now at 5f77e24c Merge #1649
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: cardano-binary-1.5.0 (user goal)
[__1] unknown package: vector (dependency of cardano-binary)
[__1] fail (backjumping, conflict set: cardano-binary, vector)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-binary, vector
```

cabal.project details below.

```
packages:
  cardano-explorer-db
  cardano-explorer-db/test
  cardano-explorer-node
  cardano-extended-db-node
  cardano-explorer-webapi
  cardano-tx-submit

constraints:
  brick >= 0.47 && < 0.50
 ,unliftio-core < 0.2.0.0
package cardano-explorer-db
  ghc-options: -Wall -Werror -fwarn-redundant-constraints

package cardano-explorer-node
  ghc-options: -Wall -Werror -fwarn-redundant-constraints

package cardano-explorer-webapi
  ghc-options: -Wall -Werror -fwarn-redundant-constraints

package cardano-tx-submit
  ghc-options: -Wall -Werror -fwarn-redundant-constraints

package cardano-binary
  tests: False

package cardano-crypto
  tests: False

package cardano-crypto-class
  tests: False

package cardano-crypto-wrapper
  tests: False

package cardano-ledger
  tests: False

package cardano-prelude
  tests: False

package cardano-shell
  tests: False

package cardano-sl-x509
  tests: False

package contra-tracer
  tests: False

package iohk-monitoring
  tests: False

package network-mux
.... 
same as repo contents
```

**Comment by erikd** [comment] 2020-03-11 22:09
This is a duplicate of #279 (and hence closing), but this one actually contains a useful warning message:
```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
```
You should treat that an error rather than as a warning. In other words, do run `cabal update`.

**Closed as completed by erikd** 2020-03-11 22:09 UTC
