### ISSUE TITLE
200OK response in error case

### ISSUE THREAD

**Issue by quietnan** [input-output-hk/cardano-explorer#259] opened 2020-02-07 16:00 UTC
For an invalid address, the `/utxos` call returns 200 OK and "Invalid address" as the sole response body. See the example below.
The http-bridge, for which this call is a replacement, had a different behaviour. There, the status code was 4xx and could be used to decide if the response body should be read as json or as plain-error string.
This feels like a regression in usability.

```
2020-02-07 16:30:06,282 DEBUG [ main] [.RestTemplatLoggingInterceptor] ===========================request begin================================================
2020-02-07 16:30:06,282 DEBUG [ main] [.RestTemplatLoggingInterceptor] URI : http://<our-cardano-explorer-1.3.0>/mainnet/utxos/Ae2tdPwUPEZMhRrCvjuGv3Zo4aSyjB31uE8CmeSmtuVFYr7N1zGEM8pvug4bla
2020-02-07 16:30:06,283 DEBUG [ main] [.RestTemplatLoggingInterceptor] Method : GET
2020-02-07 16:30:06,283 DEBUG [ main] [.RestTemplatLoggingInterceptor] Headers : [Accept:"application/json, application/*+json", Content-Length:"0"]
2020-02-07 16:30:06,288 DEBUG [ main] [.RestTemplatLoggingInterceptor] Request body:
2020-02-07 16:30:06,289 DEBUG [ main] [.RestTemplatLoggingInterceptor] ==========================request end================================================
2020-02-07 16:30:06,435 DEBUG [ main] [.RestTemplatLoggingInterceptor] ============================response begin==========================================
2020-02-07 16:30:06,436 DEBUG [ main] [.RestTemplatLoggingInterceptor] Status code : 200 OK
2020-02-07 16:30:06,436 DEBUG [ main] [.RestTemplatLoggingInterceptor] Status text : OK
2020-02-07 16:30:06,437 DEBUG [ main] [.RestTemplatLoggingInterceptor] Headers : [Date:"Fri, 07 Feb 2020 15:30:06 GMT", Server:"Warp/3.2.27", Transfer-Encoding:"chunked", Content-Type:"application/json;charset=utf-8", Via:"1.1 adnwsazh01.zh.adnovum.ch:3128 (Cisco-WSA/11.7.1-006)", Connection:"keep-alive", Proxy-Connection:"keep-alive"]
2020-02-07 16:30:06,439 DEBUG [ main] [.RestTemplatLoggingInterceptor] Response body size: 17
2020-02-07 16:30:06,439 DEBUG [ main] [.RestTemplatLoggingInterceptor] Response body: "Invalid address"
2020-02-07 16:30:06,440 DEBUG [ main] [.RestTemplatLoggingInterceptor] =======================response end=================================================
```

**Comment by erikd** [comment] 2020-02-07 21:11
@quietnan Sorry this is a duplicate of https://github.com/input-output-hk/cardano-explorer/issues/243 . Closing this.

**Closed as completed** 2020-02-07 21:39 UTC
